# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wK1eAN-ueYLBBjJ1T1kCp-ZWEncgfvdM
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
import cv2
import os

# Page configuration
st.set_page_config(
    page_title="Plant Disease Detector",
    page_icon="🌿",
    layout="wide"
)

# Custom CSS
st.markdown("""
<style>
    .main-header {
        font-size: 3rem;
        color: #2E8B57;
        text-align: center;
        margin-bottom: 2rem;
    }
    .prediction-box {
        padding: 20px;
        border-radius: 10px;
        background-color: #f0f8f0;
        border-left: 5px solid #2E8B57;
        margin: 10px 0px;
    }
    .confidence-high {
        color: #2E8B57;
        font-weight: bold;
    }
    .confidence-medium {
        color: #FFA500;
        font-weight: bold;
    }
    .confidence-low {
        color: #FF4500;
        font-weight: bold;
    }
    .model-info {
        background-color: #e8f4f8;
        padding: 15px;
        border-radius: 10px;
        border-left: 5px solid #3498db;
        margin: 10px 0px;
    }
</style>
""", unsafe_allow_html=True)

# App title
st.markdown('<h1 class="main-header">🌿 Plant Disease Detection</h1>', unsafe_allow_html=True)
st.markdown("---")

# Configuration
MODEL_PATH = "plant_disease_model.keras"
CLASS_NAMES_PATH = "class_names.txt"
IMG_SIZE = 224

@st.cache_resource
def load_model():
    """Load the trained MobileNetV2 model"""
    try:
        model = tf.keras.models.load_model(MODEL_PATH, compile=False)
        model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
        st.sidebar.success("✅ MobileNetV2 Model loaded successfully!")
        return model
    except Exception as e:
        st.sidebar.error(f"❌ Error loading model: {e}")
        return None

@st.cache_data
def load_class_names():
    """Load class names from file"""
    try:
        with open(CLASS_NAMES_PATH, 'r') as f:
            class_names = [line.strip() for line in f.readlines()]
        st.sidebar.success(f"✅ {len(class_names)} classes loaded!")
        return class_names
    except Exception as e:
        st.sidebar.error(f"❌ Error loading class names: {e}")
        return []

def preprocess_image(image):
    """Preprocess image for MobileNetV2"""
    # Convert to array and resize
    img_array = np.array(image)
    img_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))

    # Ensure 3 channels
    if len(img_array.shape) == 2:  # Grayscale
        img_array = np.stack([img_array] * 3, axis=-1)
    elif img_array.shape[2] == 4:  # RGBA
        img_array = img_array[:, :, :3]

    # Apply MobileNetV2 preprocessing (scale pixels between -1 and 1)
    img_array = tf.keras.applications.mobilenet_v2.preprocess_input(img_array)

    # Add batch dimension
    img_array = np.expand_dims(img_array, axis=0)

    return img_array

# Load model and class names
model = load_model()
class_names = load_class_names()

# Sidebar
st.sidebar.title("ℹ️ About")
st.sidebar.markdown("""
**Model Performance:**
- ✅ **89.24%** Validation Accuracy
- 🚀 **MobileNetV2** Architecture
- 🌿 **15 Plant Disease Classes**
- ⚡ **Fast Predictions**
""")

st.sidebar.markdown("---")
st.sidebar.title("📋 Instructions")
st.sidebar.markdown("""
1. Upload a clear image of a plant leaf
2. Ensure good lighting and visibility
3. Supported formats: JPG, JPEG, PNG
4. Wait for instant prediction
""")

# Main content area
col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("📤 Upload Leaf Image")
    uploaded_file = st.file_uploader(
        "Choose an image...",
        type=["jpg", "jpeg", "png"],
        help="Select a clear image of a plant leaf for accurate diagnosis"
    )

    if uploaded_file is not None:
        # Display uploaded image
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Image", use_column_width=True)

        # Image info
        with st.expander("📷 Image Details"):
            st.write(f"- **Format**: {image.format}")
            st.write(f"- **Size**: {image.size[0]} x {image.size[1]} pixels")
            st.write(f"- **Mode**: {image.mode}")

with col2:
    st.subheader("🔍 Analysis Results")

    if uploaded_file is not None and model is not None and class_names:
        try:
            with st.spinner("🔄 Analyzing image with MobileNetV2..."):
                # Preprocess image
                image_rgb = Image.open(uploaded_file).convert('RGB')
                processed_image = preprocess_image(image_rgb)

                # Make prediction
                predictions = model.predict(processed_image, verbose=0)
                predicted_class_idx = np.argmax(predictions[0])
                confidence = np.max(predictions[0]) * 100
                predicted_class = class_names[predicted_class_idx]

                # Display results
                st.markdown('<div class="prediction-box">', unsafe_allow_html=True)

                # Confidence color coding
                if confidence >= 80:
                    confidence_class = "confidence-high"
                    confidence_emoji = "🎯"
                elif confidence >= 60:
                    confidence_class = "confidence-medium"
                    confidence_emoji = "📊"
                else:
                    confidence_class = "confidence-low"
                    confidence_emoji = "🔍"

                st.markdown(f"### 🌱 **Prediction: {predicted_class}**")
                st.markdown(f"### {confidence_emoji} **Confidence: <span class='{confidence_class}'>{confidence:.2f}%</span>**", unsafe_allow_html=True)

                st.markdown('</div>', unsafe_allow_html=True)

                # Health status indicator
                if "healthy" in predicted_class.lower():
                    st.success("🎉 **Healthy Plant Detected!** This plant appears to be in good condition.")
                else:
                    st.warning("⚠️ **Potential Disease Detected!** Please consult with a plant expert for proper treatment.")

                # Top 3 predictions
                st.subheader("📊 Top Predictions")
                top_3_indices = np.argsort(predictions[0])[-3:][::-1]

                for i, idx in enumerate(top_3_indices):
                    prob = predictions[0][idx] * 100
                    bar_color = "#2E8B57" if i == 0 else "#FFA500" if i == 1 else "#3498db"

                    col_prog, col_text = st.columns([3, 7])
                    with col_prog:
                        st.progress(int(prob))
                    with col_text:
                        if i == 0:
                            st.write(f"🥇 **{class_names[idx]}**: {prob:.2f}%")
                        elif i == 1:
                            st.write(f"🥈 {class_names[idx]}: {prob:.2f}%")
                        else:
                            st.write(f"🥉 {class_names[idx]}: {prob:.2f}%")

        except Exception as e:
            st.error(f"❌ Error during prediction: {str(e)}")
            st.info("💡 Please try with a different image or check the file format.")

    elif uploaded_file is None:
        st.info("👆 **Please upload an image** to analyze plant health and detect diseases.")
        st.markdown("""
        <div class="model-info">
        <h4>🚀 Model Performance</h4>
        <ul>
        <li><b>Accuracy:</b> 89.24% on validation set</li>
        <li><b>Architecture:</b> MobileNetV2 (Optimized)</li>
        <li><b>Classes:</b> 15 plant disease types</li>
        <li><b>Speed:</b> Fast predictions for web deployment</li>
        </ul>
        </div>
        """, unsafe_allow_html=True)

# Footer
st.markdown("---")
st.markdown(
    "<div style='text-align: center; color: gray;'>"
    "🌿 Plant Disease Detection System | 89.24% Accuracy | Built with MobileNetV2 & Streamlit"
    "</div>",
    unsafe_allow_html=True
)